openapi: 3.0.0
info:
  title: WASATEXT
  description: API for WASATEXT messaging platform
  version: 1.0.0
tags:
  - name: Login
    description: Authentication operation (semplified).
  - name: User
    description: Operations related to users.
  - name: Chat
    description: Operations related to chat.
  - name: Message
    description: Operations related to messages (Managing messages).
  - name: Group
    description: Operations related to groups.


paths:
  /session:
    post:
      operationId: doLogin
      summary: Do the login.
      description: If the user exists, logs them in; otherwise, creates a new user and assigns a username.
      tags: [ "Login" ]
      requestBody:
        description: User's information.
        required: true
        content:
          application/json:
            schema:
              description: Login's schema
              type: object
              properties:
                name:
                  description: Username
                  minLength: 1
                  maxLength: 255
      responses:
        "201":
          description: Login successful
          content:
            application/json:
              schema:
                description: Login response's schema
                type: object
                properties:
                  ID:
                    description: Login identifier
                    type: integer
                    example: 21145










